---
name: Build Graph

on:
  workflow_run:
    workflows: ["Build Graph Builder"]
    types:
      - completed
  schedule:
    # run at 0400 UTC every day
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build_graph:
    runs-on: ubuntu-latest
    steps:
      - name: Download previous build-graph
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yaml
          workflow_conclusion: success
          name: build-graph
      - run: chmod +x build-graph
      - name: Run graph builder
        run: ./build-graph
        env:
          INSTANCES_SOCIAL_API_KEY: ${{ secrets.INSTANCES_SOCIAL_API_KEY }}
      - name: Upload built graph
        uses: actions/upload-artifact@v2
        with:
          name: graph
          path: graph.json
